server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: digi-doc-test-service
  profiles:
    active: ${PROFILE:local}
  servlet:
    multipart:
      maxFileSize: "-1"
      max-request-size: "512MB"

logging:
  config: classpath:log4j2-spring.xml
  level:
    com.ee.digi_doc: ${LOG_LEVEL:info}

upload:
  max-name-length: 50
  max-size: 10000000 # 10Mb in bytes

sign:
  max-file-count: 20

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /api-documentation.html

storage:
  file:
    path: /var/digi-doc-service/files
  container:
    path: /var/digi-doc-service/containers
  signing-data:
    path: /var/digi-doc-service/tmp

cleanup:
  cron.expression: "0 0 0/1 * * ?" # every hour