server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: digi-doc-test-service
  profiles:
    active: ${PROFILE:local}

logging:
  config: classpath:log4j2-spring.xml
  level:
    com.ee.digi_doc: ${LOG_LEVEL:info}

springdoc:
  api-docs:
    path: /api-documentation
  swagger-ui:
    path: /api-documentation.html

file:
  directory: /var/files